#-----------------------------------------------------------------------------------------------------------------------
# auditbeat vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

xpack_auditbeat_package: '{{ auditbeat_install_dir }}/auditbeat_{{ xpack_auditbeat_package_url | basename }}'

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
xpack_auditbeat_roles:
  xpack_auditbeat_install_config_start_verify:
    - { action: 'auditbeat_install', parent: 'auditbeat', args: {} }
    - { action: 'xpack_auditbeat_config',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
  xpack_auditbeat_config_start_verify:
    - { action: 'xpack_auditbeat_config',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
  xpack_auditbeat_install_config_start_verify_import_dashboards:
    - { action: 'auditbeat_install', parent: 'auditbeat', args: {} }
    - { action: 'xpack_auditbeat_config',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_import_dashboards', parent: 'auditbeat', args: {} }
  xpack_auditbeat_config_start_verify_import_dashboards:
    - { action: 'xpack_auditbeat_config',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_import_dashboards', parent: 'auditbeat', args: {} }
  xpack_auditbeat_rmconfig_start_verify:
    - { action: 'xpack_auditbeat_config_remove', parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
  xpack_auditbeat_install_cloud_start_verify:
    - { action: 'auditbeat_install', parent: 'auditbeat', args: {} }
    - { action: 'xpack_auditbeat_config_cloud',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }
  xpack_auditbeat_cloud_start_verify:
    - { action: 'xpack_auditbeat_config_cloud',  parent: '', args: {} }
    - { action: 'auditbeat_restart',  parent: 'auditbeat', args: {} }
    - { action: 'auditbeat_log_tail', parent: 'auditbeat', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', parent: 'auditbeat', args: {} }


# Task files for group use, keep in sync with tasks/main.yml except for parent tasks
xpack_auditbeat_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_pkg_ext }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_pkg_mgr | trim }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_srv_mgr | trim }}.yml'
