#-----------------------------------------------------------------------------------------------------------------------
# Start packetbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart packetbeat
  systemd:
      name: 'packetbeat'
      state: restarted
  become: true
