#-----------------------------------------------------------------------------------------------------------------------
# Start packetbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart packetbeat
  service:
    name: 'packetbeat'
    state: restarted
  become: true
