#-----------------------------------------------------------------------------------------------------------------------
# heartbeat vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

# Timeout
heartbeat_timeout: 60

# Extension tyoes
heartbeat_linux_package_types:
  - '.tar.gz'
  - '.deb'
  - '.rpm'

# Extension types
heartbeat_windows_package_types:
  - '.msi'
  - '.zip'

# Extract package extension
heartbeat_package_ext: "{{ heartbeat_package_url | splitext | last | regex_replace('.gz', '.tar.gz') }}"

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
heartbeat_roles:
  heartbeat_install_config_start_verify:
    - { action: 'heartbeat_install', args: {} }
    - { action: 'heartbeat_config', args: {} }
    - { action: 'heartbeat_startup', args: {} }
    - { action: 'heartbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'heartbeat_is_running', args: {} }
  heartbeat_install_config_start_verify_import_dashboards:
    - { action: 'heartbeat_install', args: {} }
    - { action: 'heartbeat_config', args: {} }
    - { action: 'heartbeat_startup', args: {} }
    - { action: 'heartbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'heartbeat_is_running', args: {} }
    - { action: 'heartbeat_import_dashboards', args: {} }
  heartbeat_shutdown_uninstall_verify:
    - { action: 'heartbeat_shutdown', args: {} }
    - { action: 'heartbeat_uninstall', args: {} }
    - { action: 'heartbeat_is_not_running', args: {} }

# Task files for group use, keep in sync with tasks/main.yml
heartbeat_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_heartbeat_pkg_ext }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_heartbeat_pkg_mgr | trim }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_heartbeat_srv_mgr | trim }}.yml'

# heartbeat log search strings
heartbeat_log_find:
  started: '.*Connection to backoff\(elasticsearch.*established'
  stopped: 'TBD'
