#-----------------------------------------------------------------------------------------------------------------------
# Uninstall Linux elasticsearch packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Uninstall elasticsearch rpm package
  yum:
    name: 'elasticsearch'
    state: absent
  become: true
  tags: uninstall_elasticsearch
