#-----------------------------------------------------------------------------------------------------------------------
# Start elasticsearch
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Start elasticsearch service
  service:
    name: 'elasticsearch'
    state: started
  become: true
  tags: start_elasticsearch
