#-----------------------------------------------------------------------------------------------------------------------
# Check if elasticsearch is not running
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Verify elasticsearch is not running
  block:
    - name: Get elasticsearch process
      shell: "ps -efw | grep elasticsearch | grep -v grep | awk '{print $2}'"
      args:
        executable: /bin/bash
      register: elasticsearch_process_id
      retries: 5
      delay: 3
      until: elasticsearch_process_id.stdout == ""
    - name: Fail if elasticsearch process is running
      fail:
        msg: 'elasticsearch is running'
      when: elasticsearch_process_id.stdout != ""
