#-----------------------------------------------------------------------------------------------------------------------
# Start elasticsearch
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart elasticsearch
  service:
    name: 'elasticsearch'
    state: restarted
  become: true
