#-----------------------------------------------------------------------------------------------------------------------
# Install Linux elasticsearch packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Download elasticsearch rpm package
  get_url:
    url: '{{ elasticsearch_package_url }}'
    dest: '{{ elasticsearch_package }}'
    timeout: '{{ url_timeout }}'
    checksum: 'sha512:{{ elasticsearch_package_url }}.sha512'
  tags: package_elasticsearch
  register: elasticsearch_get_url
  until: elasticsearch_get_url is not failed
  retries: 2
  delay: 30

- name: Install elasticsearch rpm package
  yum:
    name: '{{ elasticsearch_package }}'
    state: present
  become: true
  tags: install_elasticsearch
