#-----------------------------------------------------------------------------------------------------------------------
# Shutdown elasticsearch
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Stop elasticsearch systemd
  systemd:
      name: 'elasticsearch.service'
      state: stopped
  become: true
  tags: stop_elasticsearch
