#-----------------------------------------------------------------------------------------------------------------------
# packetbeat vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

# Timeout
packetbeat_timeout: 60

# Extension tyoes
packetbeat_linux_package_types:
  - '.tar.gz'
  - '.deb'
  - '.rpm'

# Extension types
packetbeat_windows_package_types:
  - '.msi'
  - '.zip'

# Extract package extension
packetbeat_package_ext: "{{ packetbeat_package_url | splitext | last | regex_replace('.gz', '.tar.gz') }}"

## Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
packetbeat_roles:
  packetbeat_install_config_start_verify:
    - { action: 'packetbeat_install', args: {} }
    - { action: 'packetbeat_config', args: {} }
    - { action: 'packetbeat_startup', args: {} }
    - { action: 'packetbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'packetbeat_is_running', args: {} }
  packetbeat_install_config_start_verify_import_dashboards:
    - { action: 'packetbeat_install', args: {} }
    - { action: 'packetbeat_config', args: {} }
    - { action: 'packetbeat_startup', args: {} }
    - { action: 'packetbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'packetbeat_is_running', args: {} }
    - { action: 'packetbeat_import_dashboards', args: {} }
  packetbeat_shutdown_uninstall_verify:
    - { action: 'packetbeat_shutdown', args: {} }
    - { action: 'packetbeat_uninstall', args: {} }
    - { action: 'packetbeat_is_not_running', args: {} }

# Task files for group use, keep in sync with tasks/main.yml
packetbeat_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_packetbeat_pkg_ext }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_packetbeat_pkg_mgr | trim }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_packetbeat_srv_mgr | trim }}.yml'

# packetbeat log search strings
packetbeat_log_find:
  started: '.*Connection to backoff\(elasticsearch.*established'
  stopped: 'TBD'
