#----------------------------------------------------------------------------------------------------------------------
# Variables for rpm package
#
# Author: liza.dayoub@elastic.co
#----------------------------------------------------------------------------------------------------------------------

---

# Run as root
logstash_run_as_root: true

# logstash package
logstash_package: "{{ lookup('env','AIT_VM_INSTALL_DIR') }}/{{ logstash_package_url | basename }}"

# logstash bin
logstash_bin_dir: '/usr/share/logstash/bin'
logstash_exe: '{{ logstash_bin_dir }}/logstash'
logstash_plugin_exe: '{{ logstash_bin_dir }}/logstash-plugin'

# logstash logs
logstash_log_dir: "{{ lookup('env','AIT_VM_INSTALL_DIR') }}/log/logstash"
logstash_log_file: '{{ logstash_log_dir }}/logstash.log'

# logstash config
logstash_config_dir: '/etc/logstash'
logstash_config_file: '{{ logstash_config_dir }}/logstash.yml'

# logstash conf
logstash_conf_path: '{{ logstash_config_dir }}/logstash.conf'
