#-----------------------------------------------------------------------------------------------------------------------
# Check if filebeat is not running
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Verify filebeat is not running
  block:
    - name: Get filebeat process
      shell: "ps -efw | grep filebeat | grep -v grep | awk '{print $2}'"
      args:
        executable: /bin/bash
      register: filebeat_process_id
    - name: Fail if filebeat process is running
      fail:
        msg: 'filebeat is running'
      when: filebeat_process_id.stdout != ""
