#-----------------------------------------------------------------------------------------------------------------------
# Configure filebeat on Linux
#
# Set certain parameters in filebeat configuration
#
# If a user specifies a file, it takes higher precedence
# If a user specifies filebeat_config_params_strict=True internal params are appended, otherwise they are appended
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Save original filebeat configuration
  copy:
    src: '{{ filebeat_config_file }}'
    dest: '{{ filebeat_config_file }}.org'
    remote_src: True
    force: no
  become: true

- name: Change filebeat configuration file owner to root
  file:
    path: '{{ filebeat_config_file }}'
    owner: root
    group: root
  become: true

- name: Filebeat configuration - append
  lineinfile:
    path: '{{ filebeat_config_file }}'
    insertafter: EOF
    line: '{{ config_item }}'
  with_items: '{{ filebeat_config_params  }}'
  loop_control:
    loop_var: config_item
  become: true
  when: filebeat_config_params_file is not defined and
        filebeat_config_params is defined

- name: Filebeat configuration - new file
  copy:
    src: '{{ filebeat_config_params_file }}'
    dest: '{{ filebeat_config_file }}'
  become: true
  when: filebeat_config_params_file is defined

- name: Filebeat configuration - append internal
  block:
    - name: Set network host
      set_fact:
        internal_filebeat_config_params: >
          output.elasticsearch:
             hosts: ["{{ current_host_ip }}:{{ elasticsearch_port }}"]
          setup.kibana:
            host: "{{ current_host_ip }}:{{ kibana_port }}"
    - name: Add filebeat configuration parameters
      blockinfile:
        path: '{{ filebeat_config_file }}'
        marker: '# {mark} ANSIBLE MANAGED BLOCK FILEBEAT PARAMETERS'
        insertafter: EOF
        content: '{{ internal_filebeat_config_params }}'
      become: true
  when: filebeat_config_params_strict is not defined or not filebeat_config_params_strict

- name: Enable default prospector
  replace:
    path: '{{ filebeat_config_file }}'
    regexp: '(^- type: log\n)(\n)*(^\s*#.*\n)*(\s)*(enabled: false)'
    replace: '\1\2\3\4 enabled: true'
  become: true
