#-----------------------------------------------------------------------------------------------------------------------
# Start filebeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Start filebeat systemd
  systemd:
      name: 'filebeat'
      state: started
  become: true
  tags: start_filebeat
