#-----------------------------------------------------------------------------------------------------------------------
# auditbeat vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

# Timeout
auditbeat_timeout: 60

# Extension tyoes
auditbeat_linux_package_types:
  - '.tar.gz'
  - '.deb'
  - '.rpm'

# Extension types
auditbeat_windows_package_types:
  - '.msi'
  - '.zip'

# Extract package extension
auditbeat_package_ext: "{{ auditbeat_package_url | splitext | last | regex_replace('.gz', '.tar.gz') }}"

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
auditbeat_roles:
  auditbeat_install_config_start_verify_import_dashboards:
    - { action: 'auditbeat_install', args: {} }
    - { action: 'auditbeat_config', args: {} }
    - { action: 'auditbeat_startup', args: {} }
    - { action: 'auditbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'auditbeat_is_running', args: {} }
    - { action: 'auditbeat_import_dashboards', args: {} }
  auditbeat_shutdown_uninstall_verify:
    - { action: 'auditbeat_shutdown', args: {} }
    - { action: 'auditbeat_uninstall', args: {} }
    - { action: 'auditbeat_is_not_running', args: {} }

# Task files for group use, keep in sync with tasks/main.yml
auditbeat_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_pkg_ext }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_pkg_mgr | trim }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_auditbeat_srv_mgr | trim }}.yml'

# auditbeat log search strings
auditbeat_log_find:
  started: '.*Connection to backoff\(elasticsearch.*established'
  stopped: 'TBD'
