#-----------------------------------------------------------------------------------------------------------------------
# heartbeat cloud
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------


- name: Save original heartbeat configuration
  copy:
    src: '{{ heartbeat_config_file }}'
    dest: '{{ heartbeat_config_file }}.org'
    remote_src: True
    force: no
  become: true

- name: Change heartbeat configuration file owner to root
  file:
    path: '{{ heartbeat_config_file }}'
    owner: root
    group: root
  become: true

- name: Add heartbeat x-pack configuration parameters
  blockinfile:
    path: '{{ heartbeat_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK heartbeat X-PACK PARAMETERS'
    insertafter: EOF
    content: |
      cloud.auth: "{{ elasticsearch_username }}:{{ elasticsearch_password }}"
      cloud.id: "{{ elastic_cloud_id }}"
  become: true
