#-----------------------------------------------------------------------------------------------------------------------
# heartbeat remove x-pack configuration
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------


- name: Remove heartbeat x-pack configuration
  blockinfile:
    path: '{{ heartbeat_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK HEARTBEAT X-PACK PARAMETERS'
    insertafter: EOF
    content: ""
  become: true
