#-----------------------------------------------------------------------------------------------------------------------
# Elasticsearch xpack config file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------


- name: Remove elasticsearch x-pack configuration
  blockinfile:
    path: '{{ elasticsearch_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK ELASTICSEARCH XPACK PARAMETERS'
    insertafter: EOF
    content: ""
  become: '{{ elasticsearch_run_as_root | default(omit) }}'
