#-----------------------------------------------------------------------------------------------------------------------
# Start elasticsearch
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart logstash
  systemd:
      name: 'logstash'
      state: restarted
  become: true
