#-----------------------------------------------------------------------------------------------------------------------
# Start elasticsearch
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart logstash
  service:
    name: 'logstash'
    state: restarted
  become: true
