#-----------------------------------------------------------------------------------------------------------------------
# Shutdown logstash
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Stop logstash service
  service:
    name: 'logstash'
    state: stopped
  become: true
  tags: stop_logstash
