#-----------------------------------------------------------------------------------------------------------------------
# Install Linux logstash packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Download logstash deb package
  get_url:
    url: '{{ logstash_package_url }}'
    dest: '{{ logstash_package }}'
    timeout: '{{ url_timeout }}'
    checksum: 'sha512:{{ logstash_package_url }}.sha512'
  tags: package_logstash

- name: Install logstash deb package
  apt:
    deb: '{{ logstash_package }}'
  become: true
  tags: install_logstash
