#-----------------------------------------------------------------------------------------------------------------------
# Shutdown metricbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Stop metricbeat systemd
  systemd:
      name: 'metricbeat.service'
      state: stopped
  become: true
  tags: stop_metricbeat
