#-----------------------------------------------------------------------------------------------------------------------
# Start metricbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Restart metricbeat
  service:
    name: 'metricbeat'
    state: restarted
  become: true
