#-----------------------------------------------------------------------------------------------------------------------
# Install Linux metricbeat packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Download metricbeat deb package
  get_url:
    url: '{{ metricbeat_package_url }}'
    dest: '{{ metricbeat_package }}'
    timeout: '{{ url_timeout }}'
    checksum: 'sha512:{{ metricbeat_package_url }}.sha512'
  tags: package_metricbeat

- name: Install metricbeat deb package
  apt:
    deb: '{{ metricbeat_package }}'
  become: true
  tags: install_metricbeat
