#-----------------------------------------------------------------------------------------------------------------------
# Configure metricbeat on Linux
#
# Set certain parameters in metricbeat configuration
#
# If a user specifies a file, it takes higher precedence
# If a user specifies metricbeat_config_params_strict=True internal params are appended, otherwise they are appended
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: 'metricbeat Configuration'
  blockinfile:
    path: '{{ metricbeat_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK metricbeat PARAMETERS'
    insertafter: EOF
    content: ''
  become: true
