#-----------------------------------------------------------------------------------------------------------------------
# Start metricbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Start metricbeat systemd
  systemd:
      name: 'metricbeat'
      state: started
  become: true
  tags: start_metricbeat
