#-----------------------------------------------------------------------------------------------------------------------
# Start metricbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Start metricbeat service
  service:
    name: 'metricbeat'
    state: started
  become: true
  tags: start_metricbeat
