#-----------------------------------------------------------------------------------------------------------------------
# Start metricbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Start metricbeat process
  shell: '{{ metricbeat_exe }} -c {{ metricbeat_config_file }} &'
  args:
    executable: /bin/bash
  async: 5
  poll: 0
  become: true
  tags: start_metricbeat
