#-----------------------------------------------------------------------------------------------------------------------
# Remove Kibana X-Pack Configuration
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Remove kibana x-pack configuration
  blockinfile:
    path: '{{ kibana_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK KIBANA XPACK PARAMETERS'
    insertafter: EOF
    content: ""
  become: '{{ kibana_run_as_root | default(omit) }}'
