#-----------------------------------------------------------------------------------------------------------------------
# Kibana x-pack configuration
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Copy certificates ca from localhost
  copy:
    src: "{{ local_certs_dir }}/ca"
    dest: "{{ kibana_rootdir }}"
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Copy certificates cert and key from localhost
  copy:
    src: "{{ local_certs_dir }}/node"
    dest: "{{ kibana_rootdir }}"
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Save original kibana configuration file
  copy:
    src: '{{ kibana_config_file }}'
    dest: '{{ kibana_config_file }}.org'
    remote_src: True
    force: no
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Add kibana x-pack configuration parameters
  blockinfile:
    path: '{{ kibana_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK KIBANA XPACK PARAMETERS'
    insertafter: EOF
    content: |
      elasticsearch.url: "https://{{ current_host_ip }}:{{ elasticsearch_port }}"
      elasticsearch.username: {{ kibana_username }}
      elasticsearch.password: {{ kibana_password }}
      server.ssl.enabled: true
      server.ssl.certificate: {{ kibana_rootdir | trim }}/node/node.crt
      server.ssl.key: {{ kibana_rootdir | trim }}/node/node.key
      elasticsearch.ssl.certificateAuthorities: [ '{{ kibana_rootdir | trim }}/ca/ca.crt' ]
      elasticsearch.ssl.verificationMode: none
  become: '{{ kibana_run_as_root | default(omit) }}'
