#-----------------------------------------------------------------------------------------------------------------------
# Kibana x-pack configuration
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Copy certificates ca from localhost
  copy:
    src: "{{ local_certs_dir }}/ca"
    dest: "{{ kibana_config_dir }}"
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Copy certificates cert and key from localhost
  copy:
    src: "{{ local_certs_dir }}/node"
    dest: "{{ kibana_config_dir }}"
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Save original kibana configuration
  copy:
    src: '{{ kibana_config_file }}'
    dest: '{{ kibana_config_file }}.org'
    remote_src: True
    force: no
  become: '{{ kibana_run_as_root | default(omit) }}'

- name: Create kibana log directory
  file:
    path: '{{ kibana_log_dir }}'
    state: directory
    mode: 0777
  become: true
  tags: kibana_log_check

- name: Kibana configuration - append
  lineinfile:
    path: '{{ kibana_config_file }}'
    insertafter: EOF
    line: '{{ config_item }}'
  with_items: '{{ kibana_config_params  }}'
  loop_control:
    loop_var: config_item
  become: '{{ kibana_run_as_root | default(omit) }}'
  when: kibana_config_params_file is not defined and
        kibana_config_params is defined

- name: Kibana configuration - new file
  copy:
    src: '{{ kibana_config_params_file }}'
    dest: '{{ kibana_config_file }}'
  become: '{{ kibana_run_as_root | default(omit) }}'
  when: kibana_config_params_file is defined

- name: Add kibana x-pack configuration parameters
  blockinfile:
    path: '{{ kibana_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK KIBANA XPACK PARAMETERS'
    insertafter: EOF
    content: |
      server.host:  {{ current_host_ip }}
      logging.dest: {{ kibana_log_file | trim }}
      elasticsearch.url: "https://{{ current_host_ip }}:{{ elasticsearch_port }}"
      elasticsearch.username: {{ kibana_username }}
      elasticsearch.password: {{ kibana_password }}
      server.ssl.enabled: true
      server.ssl.certificate: {{ kibana_config_dir | trim }}/node/node.crt
      server.ssl.key: {{ kibana_config_dir | trim }}/node/node.key
      elasticsearch.ssl.certificateAuthorities: [ '{{ kibana_config_dir | trim }}/ca/ca.crt' ]
      elasticsearch.ssl.verificationMode: none
  become: '{{ kibana_run_as_root | default(omit) }}'
  when: kibana_config_params_strict is not defined or not kibana_config_params_strict
