#-----------------------------------------------------------------------------------------------------------------------
# Start apm_server
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart apm_server
  systemd:
      name: 'apm_server'
      state: restarted
  become: true
