#-----------------------------------------------------------------------------------------------------------------------
# Start apm_server
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart apm_server
  service:
    name: 'apm_server'
    state: restarted
  become: true
