#-----------------------------------------------------------------------------------------------------------------------
# Start apm_server
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Start apm_server systemd
  systemd:
      name: 'apm_server'
      state: started
  become: true
  tags: start_apm_server
