#-----------------------------------------------------------------------------------------------------------------------
# Start heartbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart heartbeat
  systemd:
      name: 'heartbeat'
      state: restarted
  become: true
