#-----------------------------------------------------------------------------------------------------------------------
# Uninstall Linux heartbeat packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Uninstall heartbeat deb package
  apt:
    name: 'heartbeat'
    state: absent
    purge: true
  become: true
  tags: uninstall_heartbeat
