#-----------------------------------------------------------------------------------------------------------------------
# Start heartbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Restart heartbeat
  service:
    name: 'heartbeat'
    state: restarted
  become: true
