 #-----------------------------------------------------------------------------------------------------------------------
# Configure heartbeat on Linux
#
# Set certain parameters in heartbeat configuration
#
# If a user specifies a file, it takes higher precedence
# If a user specifies heartbeat_config_params_strict=True internal params are appended, otherwise they are appended
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Save original heartbeat configuration
  copy:
    src: '{{ heartbeat_config_file }}'
    dest: '{{ heartbeat_config_file }}.org'
    remote_src: True
    force: no
  become: true

- name: Change heartbeat configuration file owner to root
  file:
    path: '{{ heartbeat_config_file }}'
    owner: root
    group: root
  become: true

- name: Heartbeat configuration - append
  lineinfile:
    path: '{{ heartbeat_config_file }}'
    insertafter: EOF
    line: '{{ config_item }}'
  with_items: '{{ heartbeat_config_params  }}'
  loop_control:
    loop_var: config_item
  become: true
  when: heartbeat_config_params_file is not defined and
        heartbeat_config_params is defined

- name: Heartbeat configuration - new file
  copy:
    src: '{{ heartbeat_config_params_file }}'
    dest: '{{ heartbeat_config_file }}'
  become: true
  when: heartbeat_config_params_file is defined

- name: Heartbeat configuration - append internal
  block:
    - name: Set network host
      set_fact:
        internal_heartbeat_config_params: >
          output.elasticsearch:
             hosts: ["{{ current_host_ip }}:{{ elasticsearch_port }}"]
          setup.kibana:
             host: "{{ current_host_ip }}:{{ kibana_port }}"
    - name: Add heartbeat configuration parameters
      blockinfile:
        path: '{{ heartbeat_config_file }}'
        marker: '# {mark} ANSIBLE MANAGED BLOCK HEARTBEAT PARAMETERS'
        insertafter: EOF
        content: '{{ internal_heartbeat_config_params }}'
      become: true
  when: heartbeat_config_params_strict is not defined or not heartbeat_config_params_strict
