#-----------------------------------------------------------------------------------------------------------------------
# Elasticsearch vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

# Timeout
elasticsearch_timeout: 60

# Extension tyoes
elasticsearch_linux_package_types:
  - '.tar.gz'
  - '.deb'
  - '.rpm'

# Extension types
elasticsearch_windows_package_types:
  - '.msi'
  - '.zip'

elasticsearch_port: 9200
elasticsearch_username: "{{ lookup('env','AIT_ELASTICSEARCH_USERNAME') | default('elastic', true) }}"
elasticsearch_password: "{{ lookup('env','AIT_ELASTICSEARCH_PASSWORD') | default('changeme', true) }}"

# Extract package extension
elasticsearch_package_ext: "{{ elasticsearch_package_url | splitext | last | regex_replace('.gz', '.tar.gz') }}"

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
elasticsearch_roles:
  elasticsearch_install_config_start_verify:
    - { action: 'elasticsearch_install', args: {} }
    - { action: 'elasticsearch_config', args: {} }
    - { action: 'elasticsearch_startup', args: {} }
    - { action: 'elasticsearch_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'elasticsearch_api_get_info', args: {} }
  elasticsearch_shutdown_uninstall_verify:
    - { action: 'elasticsearch_shutdown', args: {} }
    - { action: 'elasticsearch_uninstall', args: {} }
    - { action: 'elasticsearch_is_not_running', args: {} }

# Task files for ait_role, keep in sync with tasks/main.yml
elasticsearch_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_elasticsearch_pkg_ext }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_elasticsearch_pkg_mgr | trim }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_elasticsearch_srv_mgr | trim }}.yml'

# elasticsearch log search strings
elasticsearch_log_find:
  started: 'Node.*started'
  stopped: 'Node.*closed'
