#----------------------------------------------------------------------------------------------------------------------
# Variables for rpm package
#
# Author: liza.dayoub@elastic.co
#----------------------------------------------------------------------------------------------------------------------

---

# Run as root
elasticsearch_run_as_root: true

# Elasticsearch package
elasticsearch_package: "{{ lookup('env','AIT_VM_INSTALL_DIR') }}/{{ elasticsearch_package_url | basename }}"

# Elasticsearch bin
elasticsearch_bin_dir: '/usr/share/elasticsearch/bin'
elasticsearch_exe: '{{ elasticsearch_bin_dir }}/elasticsearch'
elasticsearch_plugin_exe: '{{ elasticsearch_bin_dir }}/elasticsearch-plugin'
elasticsearch_certgen_exe: '{{ elasticsearch_bin_dir }}/x-pack/certgen'

# Elasticsearch logs
elasticsearch_log_dir: '/var/log/elasticsearch'
elasticsearch_log_file: '{{ elasticsearch_log_dir }}/elasticsearch.log'

# Elasticsearch config
elasticsearch_config_dir: '/etc/elasticsearch'
elasticsearch_config_file: '{{ elasticsearch_config_dir }}/elasticsearch.yml'
elasticsearch_xpack_config_dir: '{{ elasticsearch_config_dir | trim }}/x-pack'
