#-----------------------------------------------------------------------------------------------------------------------
# Install Linux auditbeat packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Download auditbeat rpm package
  get_url:
    url: '{{ auditbeat_package_url }}'
    dest: '{{ auditbeat_package }}'
    timeout: '{{ url_timeout }}'
    checksum: 'sha512:{{ auditbeat_package_url }}.sha512'
  tags: package_auditbeat
  register: auditbeat_get_url
  until: auditbeat_get_url is not failed
  retries: 2
  delay: 30

- name: Install auditbeat rpm package
  yum:
    name: '{{ auditbeat_package }}'
    state: present
  become: true
  tags: install_auditbeat
