#-----------------------------------------------------------------------------------------------------------------------
# Start auditbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart auditbeat
  block:
    - name: Stop auditbeat process
      shell: "ps -efw | grep auditbeat | grep -v grep | awk '{print $2}' | xargs kill -SIGTERM"
      args:
        executable: /bin/bash
      become: true
    - name: Start auditbeat process
      shell: '{{ auditbeat_exe }} -c {{ auditbeat_config_file }}'
      args:
        executable: /bin/bash
      become: true
      async: 5
      poll: 0
