#-----------------------------------------------------------------------------------------------------------------------
# Shutdown auditbeat
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

- name: Stop auditbeat service
  service:
    name: 'auditbeat'
    state: stopped
  become: true
  tags: stop_auditbeat
