#-----------------------------------------------------------------------------------------------------------------------
# Uninstall Linux auditbeat packages
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Uninstall auditbeat deb package
  apt:
    name: 'auditbeat'
    state: absent
    purge: true
  become: true
  tags: uninstall_auditbeat
