#-----------------------------------------------------------------------------------------------------------------------
# Configure auditbeat on Linux
#
# Set certain parameters in auditbeat configuration
#
# If a user specifies a file, it takes higher precedence
# If a user specifies auditbeat_config_params_strict=True internal params are appended, otherwise they are appended
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Save original auditbeat configuration
  copy:
    src: '{{ auditbeat_config_file }}'
    dest: '{{ auditbeat_config_file }}.org'
    remote_src: True
    force: no
  become: true

- name: Change auditbeat configuration file owner to root
  file:
    path: '{{ auditbeat_config_file }}'
    owner: root
    group: root
  become: true

- name: auditbeat configuration - append
  lineinfile:
    path: '{{ auditbeat_config_file }}'
    insertafter: EOF
    line: '{{ config_item }}'
  with_items: '{{ auditbeat_config_params  }}'
  loop_control:
    loop_var: config_item
  become: true
  when: auditbeat_config_params_file is not defined and
        auditbeat_config_params is defined

- name: auditbeat configuration - new file
  copy:
    src: '{{ auditbeat_config_params_file }}'
    dest: '{{ auditbeat_config_file }}'
  become: true
  when: auditbeat_config_params_file is defined

- name: auditbeat configuration - append internal
  block:
    - name: Set network host
      set_fact:
        internal_auditbeat_config_params: >
          output.elasticsearch:
             hosts: ["{{ current_host_ip }}:{{ elasticsearch_port }}"]
          setup.kibana:
             host: "{{ current_host_ip }}:{{ kibana_port }}"
    - name: Add auditbeat configuration parameters
      blockinfile:
        path: '{{ auditbeat_config_file }}'
        marker: '# {mark} ANSIBLE MANAGED BLOCK auditbeat PARAMETERS'
        insertafter: EOF
        content: '{{ internal_auditbeat_config_params }}'
      become: true
  when: auditbeat_config_params_strict is not defined or not auditbeat_config_params_stric
