#-----------------------------------------------------------------------------------------------------------------------
# Kibana x-pack vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

# x-pack kibana package
xpack_kibana_package: '{{ kibana_install_dir }}/kibana_{{ xpack_kibana_package_url | basename }}'

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
xpack_kibana_roles:
  xpack_kibana_install_config_start_verify:
    - { action: 'kibana_install',  parent: 'kibana', args: {} }
    - { action: 'xpack_kibana_install', parent: '', args: {} }
    - { action: 'kibana_config',  parent: 'kibana', args: {} }
    - { action: 'xpack_kibana_config',  parent: '', args: {} }
    - { action: 'kibana_restart',  parent: 'kibana', args: {} }
    - { action: 'kibana_log_tail', parent: 'kibana', args: {ait_log_searchstr: started} }
    - { action: 'kibana_is_running', parent: 'kibana', args: {} }
  xpack_kibana_plugin_config_start_verify:
    - { action: 'xpack_kibana_install', parent: '', args: {} }
    - { action: 'xpack_kibana_config',  parent: '', args: {} }
    - { action: 'kibana_restart',  parent: 'kibana', args: {} }
    - { action: 'kibana_log_tail', parent: 'kibana', args: {ait_log_searchstr: started} }
    - { action: 'kibana_is_running', parent: 'kibana', args: {} }
  xpack_kibana_plugin_rmconfig_uninstall_start_verify:
    - { action: 'xpack_kibana_config_remove', parent: '', args: {} }
    - { action: 'xpack_kibana_uninstall', parent: '', args: {} }
    - { action: 'kibana_restart',  parent: 'kibana', args: {} }
    - { action: 'kibana_log_tail', parent: 'kibana', args: {ait_log_searchstr: started} }
    - { action: 'kibana_is_running', parent: 'kibana', args: {} }

# Task files for ait_role, keep in sync with tasks/main.yml except for parent tasks
xpack_kibana_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_kibana_pkg_ext }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_kibana_pkg_mgr | trim }}.yml'
  - '../{{ item.parent }}/tasks/{{ ansible_system | lower }}/{{ item.action }}_{{ ait_kibana_srv_mgr | trim }}.yml'
