#-----------------------------------------------------------------------------------------------------------------------
# metricbeat vars file
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------

---

# Timeout
metricbeat_timeout: 60

# Extension tyoes
metricbeat_linux_package_types:
  - '.tar.gz'
  - '.deb'
  - '.rpm'

# Extension types
metricbeat_windows_package_types:
  - '.msi'
  - '.zip'

# Extract package extension
metricbeat_package_ext: "{{ metricbeat_package_url | splitext | last | regex_replace('.gz', '.tar.gz') }}"

# Variables to run multiple role task files in a group
# Must have role name (key), action and args that map to individual task files
metricbeat_roles:
  metricbeat_install_config_start_verify:
    - { action: 'metricbeat_install', args: {} }
    - { action: 'metricbeat_config', args: {} }
    - { action: 'metricbeat_startup', args: {} }
    - { action: 'metricbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'metricbeat_is_running', args: {} }
  metricbeat_install_config_start_verify_import_dashboards:
    - { action: 'metricbeat_install', args: {} }
    - { action: 'metricbeat_config', args: {} }
    - { action: 'metricbeat_startup', args: {} }
    - { action: 'metricbeat_log_tail', args: {ait_log_searchstr: started} }
    - { action: 'metricbeat_is_running', args: {} }
    - { action: 'metricbeat_import_dashboards', args: {} }
  metricbeat_shutdown_uninstall_verify:
    - { action: 'metricbeat_shutdown', args: {} }
    - { action: 'metricbeat_uninstall', args: {} }
    - { action: 'metricbeat_is_not_running', args: {} }

# Task files for group use, keep in sync with tasks/main.yml
metricbeat_task_files:
  - '{{ ansible_system | lower }}/{{ item.action }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_metricbeat_pkg_ext }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_metricbeat_pkg_mgr | trim }}.yml'
  - '{{ ansible_system | lower }}/{{ item.action }}_{{ ait_metricbeat_srv_mgr | trim }}.yml'

# metricbeat log search strings
metricbeat_log_find:
  started: '.*Connection to backoff\(elasticsearch.*established'
  stopped: 'TBD'