#-----------------------------------------------------------------------------------------------------------------------
# Restart Kibana
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Restart kibana
  systemd:
      name: 'kibana'
      state: restarted
  become: true
