#----------------------------------------------------------------------------------------------------------------------
# Variables for deb package
#
# Author: liza.dayoub@elastic.co
#----------------------------------------------------------------------------------------------------------------------

---

# Run as root
kibana_run_as_root: true

# kibana package
kibana_package: "{{ lookup('env','AIT_VM_INSTALL_DIR') }}/{{ kibana_package_url | basename }}"

# kibana bin
kibana_bin_dir: '/usr/share/kibana/bin'
kibana_exe: '{{ kibana_bin_dir }}/kibana'
kibana_plugin_exe: '{{ kibana_bin_dir }}/kibana-plugin'

# kibana logs
kibana_log_dir: '/var/log/kibana'
kibana_log_file: '{{ kibana_log_dir }}/kibana.log'

# kibana config
kibana_config_dir: '/etc/kibana'
kibana_config_file: '{{ kibana_config_dir }}/kibana.yml'
