#-----------------------------------------------------------------------------------------------------------------------
# Metricbeat cloud
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------


- name: Save original metricbeat configuration
  copy:
    src: '{{ metricbeat_config_file }}'
    dest: '{{ metricbeat_config_file }}.org'
    remote_src: True
    force: no
  become: true

- name: Change metricbeat configuration file owner to root
  file:
    path: '{{ metricbeat_config_file }}'
    owner: root
    group: root
  become: true

- name: Add metricbeat x-pack configuration parameters
  blockinfile:
    path: '{{ metricbeat_config_file }}'
    marker: '# {mark} ANSIBLE MANAGED BLOCK METRICBEAT X-PACK PARAMETERS'
    insertafter: EOF
    content: |
      cloud.auth: "{{ elasticsearch_username }}:{{ elasticsearch_password }}"
      cloud.id: "{{ elastic_cloud_id }}"
  become: true
